#### Section A: Data Structures & Control Structures

##### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
lst = [1,2,3,4,5]
print("Original List: ", lst)
lst.append(6)
print("After append(6): ", lst)
lst.extend([7])
print("After extend([7]): ", lst)
lst.insert(2,2.5)
print("After Insert(2,2.5): ", lst)
lst.remove(2.5)
print("After remove(2.5): ", lst)
lst.pop()
print("After pop(): ", lst)
print("Index of 4: ", lst.index(4))
lst.extend([6,8,6,11])
print("count of 6: ", lst.count(6))
lst.sort()
print("After Sort(): ", lst)
lst.reverse()
print("After Reverse(): ", lst)
lst.clear()
print("After clear(): ", lst)

Original List:  [1, 2, 3, 4, 5]
After append(6):  [1, 2, 3, 4, 5, 6]
After extend([7]):  [1, 2, 3, 4, 5, 6, 7]
After Insert(2,2.5):  [1, 2, 2.5, 3, 4, 5, 6, 7]
After remove(2.5):  [1, 2, 3, 4, 5, 6, 7]
After pop():  [1, 2, 3, 4, 5, 6]
Index of 4:  3
count of 6:  3
After Sort():  [1, 2, 3, 4, 5, 6, 6, 6, 8, 11]
After Reverse():  [11, 8, 6, 6, 6, 5, 4, 3, 2, 1]
After clear():  []


##### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
stu = ('Rak','Mur','Aml')
print("Original Tuple: ", stu)
stu[1] = "Akh"
print("Updated Tuple: ", stu)

Original Tuple:  ('Rak', 'Mur', 'Aml')


TypeError: 'tuple' object does not support item assignment

###### Explanation: Tuples are immutable, their elements cannot be changed once they are created 

##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
st = {1,1,1,2,3,4,4,5,6,7,8,8,9}
print("Set: ", st)

Set:  {1, 2, 3, 4, 5, 6, 7, 8, 9}


###### Explaination: Set stores only Unique values. Duplicate values are automatically removed, so each elements appears only once

##### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
dct = {'name':'Rak',
      'age': 24,
      'city': 'Bangalore'}
print("Original Dictionary: ", dct)
dct['age'] = 23
dct['email'] = 'rak@xyz.com'
print("\nUpdated Dictionary: ", dct)

Original Dictionary:  {'name': 'Rak', 'age': 24, 'city': 'Bangalore'}

Updated Dictionary:  {'name': 'Rak', 'age': 23, 'city': 'Bangalore', 'email': 'rak@xyz.com'}


##### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:
age = int(input("Enter your age: "))
if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter your age:  22


You are eligible to vote


#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [6]:
marks = int(input("Enter your marks"))
if marks >= 90:
    print("Your grade is 'A' ")
elif marks >= 75:
    print("Your grade is 'B' ")
elif marks >= 50:
    print("Your grade is 'C' ")
else:
    print("You have failed")

Enter your marks 91


Your grade is 'A' 


##### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
n = int(input("Enter a number: "))
if n > 0:
    if n % 2 == 0:
        print("The number is positive and even")
    else:
        print("The number is positive and odd")
elif n == 0:
    print("The number is zero")
else:
    print("The number is negative")

Enter a number:  36


The number is positive and even


#### Section B: Numpy

##### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [8]:
import numpy as np
scalar = np.array(5)
print("Scalar:", scalar)

arr1d = np.array([1,2,3,4,5])
print("\n1D array:",arr1d)

arr2d = np.array([[10,20,30],
                  [40,50,60]])
print("\n2D array:")
print(arr2d)

Scalar: 5

1D array: [1 2 3 4 5]

2D array:
[[10 20 30]
 [40 50 60]]


##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [9]:
arr4_4 = np.random.randint(0,101, (4,4))
print("4x4 array of random integers:")
print(arr4_4)

4x4 array of random integers:
[[18 94 49  8]
 [36 42 20 49]
 [ 8 73 43 37]
 [28  9  9 88]]


##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [10]:
import pandas as pd
arr2d = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
df = pd.DataFrame(arr2d, columns=['A','B','C'])
df

,A,B,C
0,10,20,30
1,40,50,60
2,70,80,90


#### Section C: Exploring Pandas

##### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [11]:
data = pd.DataFrame({
    'Name':['Rakshith','Akhil','Amal','Sanskar','Wrishab','Sharan','Rupesh','Siddarth','Tharun','Rakshith'],
    'Age': [23,24,25,21,25,21,21,22,23,23],
    'City':['Bangalore','Hyderabad','Thiruvananthapuram','Puri','Cuttack','Puducherry','Mysuru','Coimbatore','Kochi','Bangalore'],
    'Salary':[90000,80000,85000,90000,80000,np.nan,70000,np.nan,87000,90000]
})
print("Original DataFrame:\n")
print(data)
print("\nDataframe Info:\n")
print(data.info())
print("\nData Description:\n")
print(data.describe())
print("\nName & City Column:\n")
print(data[['Name','City']])
data = data.drop("City", axis=1)
print("\nAfter dropping city column\n")
print(data)
data['Salary'] = data['Salary'].fillna(data['Salary'].mean())
print("\nAfter filling missing Salary with mean\n")
print(data)
duplicates = data[data.duplicated()]
print("\n Duplicates\n",duplicates)
data = data.drop_duplicates()
print("\nAfter removing duplicated rows:")
print(data)

Original DataFrame:

       Name  Age                City   Salary
0  Rakshith   23           Bangalore  90000.0
1     Akhil   24           Hyderabad  80000.0
2      Amal   25  Thiruvananthapuram  85000.0
3   Sanskar   21                Puri  90000.0
4   Wrishab   25             Cuttack  80000.0
5    Sharan   21          Puducherry      NaN
6    Rupesh   21              Mysuru  70000.0
7  Siddarth   22          Coimbatore      NaN
8    Tharun   23               Kochi  87000.0
9  Rakshith   23           Bangalore  90000.0

Dataframe Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Data Description:

             Age      Salary
count  10.0